# Generated by Django 3.1.4 on 2021-02-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('surname', models.CharField(max_length=50, verbose_name='surname')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('num_title', models.CharField(choices=[('050', '050'), ('051', '051'), ('055', '055'), ('070', '070'), ('077', '077'), ('099', '099')], max_length=10, verbose_name='num title')),
                ('tel_number', models.CharField(max_length=20, verbose_name='telefon')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'checkout',
                'verbose_name_plural': 'checkout',
                'db_table': 'checkout',
            },
        ),
    ]
