# Generated by Django 3.1.4 on 2021-02-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='tel_number',
            field=models.IntegerField(max_length=7, verbose_name='telefon'),
        ),
    ]
