# Generated by Django 3.1.4 on 2021-02-24 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210224_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='tel_number',
            field=models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='telefon'),
        ),
    ]
