# Generated by Django 3.1.4 on 2021-02-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210224_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='num_title',
            field=models.CharField(choices=[('---', '---'), ('050', '050'), ('051', '051'), ('055', '055'), ('070', '070'), ('077', '077'), ('099', '099')], max_length=10, verbose_name='num title'),
        ),
    ]
