# Generated by Django 3.1.4 on 2021-04-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='facebook',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='instagram',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
