# Generated by Django 2.2.8 on 2021-05-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210427_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='internal_storage',
            field=models.IntegerField(blank=True, default=None, max_length=20, null=True, verbose_name='Daxili yaddaş'),
        ),
    ]
