# Generated by Django 2.2.8 on 2021-05-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210521_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='internal_storage',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Daxili yaddaş'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Operativ yaddaş'),
        ),
    ]
