# Generated by Django 2.2.8 on 2021-05-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210521_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='internal_storage',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Daxili yaddaş (GB)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Operativ yaddaş (GB)'),
        ),
    ]
