# Generated by Django 3.1.4 on 2021-02-22 23:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_code',
            field=colorfield.fields.ColorField(blank=True, default='', max_length=18, null=True, verbose_name='Color code'),
        ),
    ]
