# Generated by Django 3.1.4 on 2021-02-23 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210222_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_details_property_name',
            old_name='content',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='product_details_property_name',
            name='file',
        ),
    ]
