# Generated by Django 3.1.4 on 2021-02-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210223_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_details_property_name',
            old_name='title',
            new_name='content',
        ),
        migrations.AddField(
            model_name='product_details_property_name',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='products_files', verbose_name='File'),
        ),
    ]
