# Generated by Django 3.1.4 on 2021-02-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210223_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_details',
            old_name='Product_details_property_name',
            new_name='product_details_property_name',
        ),
        migrations.AddField(
            model_name='product_details',
            name='is_detail',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is detail'),
        ),
        migrations.AddField(
            model_name='product_details',
            name='is_feature',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is feature'),
        ),
        migrations.AddField(
            model_name='product_details',
            name='is_file',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is file'),
        ),
    ]
