# Generated by Django 3.1.4 on 2021-02-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210223_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='product_details_propert_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details_property_value', to='product.product_details_property_value'),
        ),
    ]
