# Generated by Django 3.1.4 on 2021-02-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210223_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_images',
            options={'ordering': ('-created_at',), 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=110, unique=True, verbose_name='Slug'),
        ),
    ]
