# Generated by Django 3.1.4 on 2021-02-27 20:00

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210223_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, size=[500, 300], upload_to='product_images'),
        ),
    ]
